// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PracticaDobosh.DAL.Context;

#nullable disable

namespace PracticaDobosh.Migrations
{
    [DbContext(typeof(EquipmentDbContext))]
    partial class EquipmentDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PracticaDobosh.DAL.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HeadOfDepartment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("PracticaDobosh.DAL.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("FIO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("PracticaDobosh.DAL.Entities.Equipment", b =>
                {
                    b.Property<string>("InventoryNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("EquipmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EquipmentTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.HasKey("InventoryNumber");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("EquipmentTypeId");

                    b.ToTable("Equipments");
                });

            modelBuilder.Entity("PracticaDobosh.DAL.Entities.EquipmentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EquipmentTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EquipmentTypes");
                });

            modelBuilder.Entity("PracticaDobosh.DAL.Entities.InstalledSoftware", b =>
                {
                    b.Property<string>("EquipmentInventoryNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("LicenseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("InstallonDate")
                        .HasColumnType("datetime2");

                    b.HasKey("EquipmentInventoryNumber", "LicenseId");

                    b.HasIndex("LicenseId");

                    b.ToTable("InstalledSoftwares");
                });

            modelBuilder.Entity("PracticaDobosh.DAL.Entities.MovementHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EquipmentInventoryNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("MovementDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("NewEmployeeId")
                        .HasColumnType("int");

                    b.Property<int?>("OldEmployeeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentInventoryNumber");

                    b.HasIndex("NewEmployeeId");

                    b.HasIndex("OldEmployeeId");

                    b.ToTable("MovementHistories");
                });

            modelBuilder.Entity("PracticaDobosh.DAL.Entities.SoftwareLicenses", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LicenseKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoftwareName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SoftwareLicenses");
                });

            modelBuilder.Entity("PracticaDobosh.DAL.Entities.Employee", b =>
                {
                    b.HasOne("PracticaDobosh.DAL.Entities.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("PracticaDobosh.DAL.Entities.Equipment", b =>
                {
                    b.HasOne("PracticaDobosh.DAL.Entities.Employee", "ResponsibleEmployee")
                        .WithMany("ResponsibleEquipment")
                        .HasForeignKey("EmployeeId");

                    b.HasOne("PracticaDobosh.DAL.Entities.EquipmentType", "EquipmentType")
                        .WithMany("Equipments")
                        .HasForeignKey("EquipmentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EquipmentType");

                    b.Navigation("ResponsibleEmployee");
                });

            modelBuilder.Entity("PracticaDobosh.DAL.Entities.InstalledSoftware", b =>
                {
                    b.HasOne("PracticaDobosh.DAL.Entities.Equipment", "Equipment")
                        .WithMany("InstalledSoftware")
                        .HasForeignKey("EquipmentInventoryNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PracticaDobosh.DAL.Entities.SoftwareLicenses", "License")
                        .WithMany("InstalledSoftware")
                        .HasForeignKey("LicenseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipment");

                    b.Navigation("License");
                });

            modelBuilder.Entity("PracticaDobosh.DAL.Entities.MovementHistory", b =>
                {
                    b.HasOne("PracticaDobosh.DAL.Entities.Equipment", "Equipment")
                        .WithMany("MovementHistory")
                        .HasForeignKey("EquipmentInventoryNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PracticaDobosh.DAL.Entities.Employee", "NewEmployee")
                        .WithMany("NewMovements")
                        .HasForeignKey("NewEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PracticaDobosh.DAL.Entities.Employee", "OldEmployee")
                        .WithMany("OldMovements")
                        .HasForeignKey("OldEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Equipment");

                    b.Navigation("NewEmployee");

                    b.Navigation("OldEmployee");
                });

            modelBuilder.Entity("PracticaDobosh.DAL.Entities.Department", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("PracticaDobosh.DAL.Entities.Employee", b =>
                {
                    b.Navigation("NewMovements");

                    b.Navigation("OldMovements");

                    b.Navigation("ResponsibleEquipment");
                });

            modelBuilder.Entity("PracticaDobosh.DAL.Entities.Equipment", b =>
                {
                    b.Navigation("InstalledSoftware");

                    b.Navigation("MovementHistory");
                });

            modelBuilder.Entity("PracticaDobosh.DAL.Entities.EquipmentType", b =>
                {
                    b.Navigation("Equipments");
                });

            modelBuilder.Entity("PracticaDobosh.DAL.Entities.SoftwareLicenses", b =>
                {
                    b.Navigation("InstalledSoftware");
                });
#pragma warning restore 612, 618
        }
    }
}
